// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/GearCatchCommands.h"
#include "Commands/RunHexapus.h"
#include "Commands/RunIntake.h"
#include "Commands/RunShooter.h"
#include "Commands/RunWinch.h"
#include "Commands/ToggleLights.h"

class HexapusButton : public JoystickButton {
  // bool buttonReleased = false;
  bool jamDetected = false;

 public:
  HexapusButton(GenericHID* joystick, int buttonNumber)
      : JoystickButton(joystick, buttonNumber) {}

  bool Get() override {
    bool buttonPressed = JoystickButton::Get();
    if (buttonPressed) {
      if (jamDetected) {
        return false;
      } else {
        bool jam = Robot::shooter->isHexapusJammed();
        if (jam) {
          jamDetected = true;
          return false;
        }
      }
    } else {
      if (jamDetected) {
        jamDetected = false;
      }
      return JoystickButton::Get();
    }
    // shouldnt get here:
    return JoystickButton::Get() && !Robot::shooter->isHexapusJammed();
  }
};

class RotateFront : public InstantCommand {
  DriveWithJoystick* drive = new DriveWithJoystick();

 protected:
  void Initialize() override {
    drive->Start();
    drive->toggle();
  }

  void Execute() override {}
  void End() {}
};



// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * Operator Input Setup
 * ====================
 *
 * Driver Joystick
 * ------------------
 * 	-Toggle pickup: button 2
 * 	-switch robot front: button 1
 * 	-rope climb: button 5 - go up while held, hold on release
 * 	-driving: x,y,twist
 *
 * 	Secondary Joystick
 * 	---------------------
 * 	-shoot(toggle hexapus): button 1
 * 	-shoot(toggle flywheel): button 2
 * 	-shoot(flywheel speed): throttle
 * 	-shoot(hexapus unjam/go backwards a little): button 4
 * 	-Gear Catch Toggle(in/out): button 3
 *
 */
OI::OI() {
  // Process operator interface input here.
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
  driverJoystick.reset(new DriverJoystick());
  shooterJoystick.reset(new ShooterJoystick());

  driverWinchUp.reset(new JoystickButton(driverJoystick.get(), 8));
  driverWinchUp->WhileHeld(RunWinch::createGoUpCommand());
  driverWinchUp->WhenReleased(RunWinch::createHoldCommand());

  shooterWinchDown.reset(new JoystickButton(shooterJoystick.get(), 9));
  shooterWinchDown->WhileHeld(RunWinch::createDownCommand());

  shooterWinchZero.reset(new JoystickButton(shooterJoystick.get(), 10));
  shooterWinchZero->WhenPressed(RunWinch::createDownCommand());

  shooterWinchUp.reset(new JoystickButton(shooterJoystick.get(), 11));
  shooterWinchUp->WhileHeld(RunWinch::createGoUpCommand());
  shooterWinchUp->WhenReleased(RunWinch::createHoldCommand());

  driverBallIntake.reset(new JoystickButton(driverJoystick.get(), 3));
  driverBallIntake->WhileHeld(new RunIntake());
  driverChangeFront.reset(new JoystickButton(driverJoystick.get(), 1));
  driverChangeFront->WhenPressed(new RotateFront());


  shooterShoot.reset(new JoystickButton(shooterJoystick.get(), 2));
  shooterShoot->ToggleWhenPressed(new RunShooter());

  shooterRunHexapus.reset(new HexapusButton(shooterJoystick.get(), 1));
  shooterRunHexapus->WhileHeld(new RunHexapus());
  shooterRunHexapus->WhenReleased(new ReAddDefaultHexapusCommand());

  gearCatchToggle.reset(new JoystickButton(shooterJoystick.get(), 5));
  gearCatchToggle->WhenPressed(new GearCatchToggle());

  shooterGearCatchOut.reset(new JoystickButton(shooterJoystick.get(), 6));
  shooterGearCatchOut->WhenPressed(new GearCatchOut());


  shooterUnjam.reset(new JoystickButton(shooterJoystick.get(), 7));
  shooterUnjam->WhenPressed(RunHexapus::createUnjamCommand());
  // shooterUnjam->WhenReleased(new ReAddDefaultHexapusCommand());

  shooterRunIntake.reset(new JoystickButton(shooterJoystick.get(), 3));
  shooterRunIntake->WhileHeld(new RunIntake());

  initSmartDashboardCommands();

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

void OI::initSmartDashboardCommands() {
  // SmartDashboard Buttons
  SmartDashboard::PutData("RunIntake", new RunIntake());
  SmartDashboard::PutData("RunWinch: down", RunWinch::createDownCommand());
  SmartDashboard::PutData("RunWinch: up", RunWinch::createGoUpCommand());
  SmartDashboard::PutData("RunWinch: upslow", RunWinch::createHoldCommand());
  SmartDashboard::PutData("RunShooter", new RunShooter());
  SmartDashboard::PutData("DriveWithJoystick", new DriveWithJoystick());
  SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
  SmartDashboard::PutData("Hexapus", new RunHexapus());
  //
  SmartDashboard::PutData("Gear catch: in (undriven)",
                          new GearCatchInUnpowered());
  SmartDashboard::PutData("gear catch: toggle", new GearCatchToggle());
  SmartDashboard::PutData("Gear catch: in", new GearCatchIn());
  SmartDashboard::PutData("Gear catch: out", new GearCatchOut());
  SmartDashboard::PutData("Toggle lights", new ToggleLights());
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriverJoystick() {
  return driverJoystick;
}

std::shared_ptr<Joystick> OI::getShooterJoystick() {
  return shooterJoystick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

ReAddDefaultHexapusCommand::ReAddDefaultHexapusCommand() : InstantCommand() {}

void ReAddDefaultHexapusCommand::Exeute() {
  Robot::oi->shooterRunHexapus->WhileHeld(new RunHexapus());
}
Btn::Btn(Joystick* j, int b) : joystick(j), buttonNumber(b) {}

bool Btn::Get() {
  return joystick->GetRawButton(buttonNumber);
}

DriverJoystick::DriverJoystick()
    : Joystick(0),
      winchUp(new Btn(this, 8)),
      ballIntake(new Btn(this, 3)),
      changeFront(new Btn(this, 1)) {

  winchUp->WhileHeld(RunWinch::createGoUpCommand());
  winchUp->WhenReleased(RunWinch::createHoldCommand());
  ballIntake->WhileHeld(new RunIntake());
  changeFront->WhenPressed(new RotateFront());
}

ShooterJoystick::ShooterJoystick()
    : Joystick(1),
      winchUp(new Btn(this, 11)),
      winchDown(new Btn(this, 9)),
      winchStop(new Btn(this, 10)),
      runHexapus(new Btn(this, 1)),
      runIntake(new Btn(this, 3)),
      shoot(new Btn(this, 2)),
      unjam(new Btn(this, 7)),
      gearCatchIn(new Btn(this, 5)),
      gearCatchOut(new Btn(this, 6))
{

  winchDown->WhileHeld(RunWinch::createDownCommand());
  winchStop->WhenPressed(RunWinch::createDownCommand());
  winchUp->WhileHeld(RunWinch::createGoUpCommand());
  winchUp->WhenReleased(RunWinch::createHoldCommand());
  shoot->ToggleWhenPressed(new RunShooter());
  runIntake->WhileHeld(new RunIntake());


  gearCatchIn->WhenPressed(new GearCatchIn());
  gearCatchOut->WhenPressed(new GearCatchOut());
}
