// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef OI_H
#define OI_H

#include "WPILib.h"

class Btn : public Button {

public:
    Btn(Joystick *joystick,int buttonNumber);

    bool Get() override;
    Joystick* joystick;
    int buttonNumber;

};
class DriverJoystick : public Joystick {
public:
    DriverJoystick();

    Btn* winchUp;
    Btn* ballIntake;
    Btn* changeFront;


};
class ShooterJoystick : public Joystick {
public:
    ShooterJoystick();

    Btn* winchUp;
    Btn* winchDown;
    Btn* winchStop;
    Btn* runHexapus;
    Btn* runIntake;
    Btn* shoot;
    Btn* unjam;
    Btn* gearCatchIn;
    Btn* gearCatchOut;

};

class OI {
  friend class ReAddDefaultHexapusCommand;

 public:
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  std::shared_ptr<DriverJoystick> driverJoystick;
  std::shared_ptr<ShooterJoystick> shooterJoystick;
  // driver buttons

  std::shared_ptr<JoystickButton> shooterWinchDown;
  std::shared_ptr<JoystickButton> driverWinchUp;
  std::shared_ptr<JoystickButton> shooterRunHexapus;
  std::shared_ptr<JoystickButton> driverChangeFront;

  // shooter buttons
  std::shared_ptr<JoystickButton> shooterShoot;
  std::shared_ptr<JoystickButton> shooterGearCatchOut;
  std::shared_ptr<JoystickButton> gearCatchToggle;
  std::shared_ptr<JoystickButton> shooterGearIntakeToggle;
  std::shared_ptr<JoystickButton> driverBallIntake;
  std::shared_ptr<JoystickButton> shooterUnjam;
  std::shared_ptr<JoystickButton> shooterRunIntake;

  std::shared_ptr<JoystickButton> shooterWinchZero;
  std::shared_ptr<JoystickButton> shooterWinchUp;

  void initSmartDashboardCommands();

 public:
  OI();

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

  std::shared_ptr<Joystick> getDriverJoystick();

  std::shared_ptr<Joystick> getShooterJoystick();
};
class ReAddDefaultHexapusCommand : public InstantCommand {
    friend class OI;

public:
    ReAddDefaultHexapusCommand();

    virtual void Exeute();
};
#endif
