// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "DriveWithJoystick.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveWithJoystick::DriveWithJoystick() : Command() {

  Requires(Robot::chassis.get());
}



// Called repeatedly when this Command is scheduled to run
void DriveWithJoystick::Execute() {
 // double angle = rotate ? 90.0 : 0.0;

  Robot::chassis->MecanumDrive(Robot::oi->driverJoystick);
}

// Make this return true when this Command no longer needs to run execute()
bool DriveWithJoystick::IsFinished() {
  return false;
}


// Called when another command which requires one or more of the same
// subsystems is scheduled to run
//void DriveWithJoystick::Interrupted() {
//  End();
//}

//DriveWithJoystick::DriveWithJoystick(bool r) : rotate(r) {}

//void DriveWithJoystick::toggle() {
//  rotate = !rotate;
//}
