// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef RUNWINCH_H
#define RUNWINCH_H

#include <Commands/Command.h>

class RunWinch : public Command {
 public:
  virtual void Initialize();
  virtual void Execute();
  virtual bool IsFinished();
  virtual void End();
  virtual void Interrupted();

  static RunWinch* createGoUpCommand();
  static RunWinch* createHoldCommand();
  static RunWinch* createDownCommand();
    static RunWinch* createStopCommand();

 protected:
  RunWinch(double speed);

 private:
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

  double m_speed;

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};

#endif
